### ISSUE TITLE
Fix SMPTE XML Namespaces ABNF

### ISSUE THREAD

**Issue by thomasheritage** [SMPTE/ag-05#4]
## Problem

In [SMPTE AG-05:2018](https://f.hubspotusercontent00.net/hubfs/5253154/Standards%20Files/AG-05-XML-in-Engineering-Documents.pdf), Clause 5.4.1 contains this ABNF (partial extract):
```
NS = %s"http://www.smpte-ra.org/ns/" PUBNUM "/" REVISION [ "/" SHORTNAME]
SHORTNAME = 1*4("/" 1*(ALPHA / DIGIT / "-" / "_" / ".") )
```
This means that examples such as:
```
http://www.smpte-ra.org/ns/456/2005/foo
```
are not valid. It would need to be:
```
http://www.smpte-ra.org/ns/456/2005//foo
```

## Solution
Replace:
```
NS = %s"http://www.smpte-ra.org/ns/" PUBNUM "/" REVISION [ "/" SHORTNAME]
```
with
```
NS = %s"http://www.smpte-ra.org/ns/" PUBNUM "/" REVISION [SHORTNAME]
```

**Comment by SteveLLamb** [comment]
Closed via #7
